const TABLE='forma_design_production_jobs';
const ALLOWED_SOURCE_TYPES=new Set(['url','text','topic','project']);
const ALLOWED_STAGES=new Set(['queued','source','reading','evidence','translation','generating','quality','fallback','ready','failed','cancelled']);
const TRACKING_KEYS=new Set(['fbclid','gclid','dclid','mc_cid','mc_eid','igshid','ref_src','ref_url','srsltid']);
function json(data,status=200){return Response.json(data,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});}
function clean(value,max=5000){return String(value??'').trim().slice(0,max);}
function now(){return new Date().toISOString();}
function id(){return crypto.randomUUID();}
function clamp(value,min,max){return Math.max(min,Math.min(max,Number(value)||min));}
function parseJson(value,fallback={}){try{return JSON.parse(value||'')??fallback;}catch{return fallback;}}
async function ensure(db){if(!db)return false;await db.prepare(`CREATE TABLE IF NOT EXISTS ${TABLE}(
  id TEXT PRIMARY KEY,source_type TEXT NOT NULL,title TEXT NOT NULL DEFAULT '',input_payload TEXT NOT NULL,normalized_input TEXT NOT NULL DEFAULT '{}',
  status TEXT NOT NULL,stage TEXT NOT NULL,progress INTEGER NOT NULL DEFAULT 0,attempt INTEGER NOT NULL DEFAULT 1,retry_count INTEGER NOT NULL DEFAULT 0,
  heartbeat TEXT NOT NULL,output_payload TEXT NOT NULL DEFAULT '{}',error_payload TEXT NOT NULL DEFAULT '{}',reader_strategy TEXT NOT NULL DEFAULT '',
  evidence_count INTEGER NOT NULL DEFAULT 0,quality_score REAL,confidence REAL,engine_baseline TEXT NOT NULL DEFAULT 'forma-production-v1',created_at TEXT NOT NULL,updated_at TEXT NOT NULL
)`).run();await db.prepare(`CREATE INDEX IF NOT EXISTS idx_${TABLE}_updated ON ${TABLE}(updated_at DESC)`).run();await db.prepare(`CREATE INDEX IF NOT EXISTS idx_${TABLE}_status ON ${TABLE}(status,updated_at DESC)`).run();return true;}
function normalizeUrl(value){const original=clean(value,4000);let url;try{url=new URL(original);}catch{throw new Error('URL inválida.');}if(!['http:','https:'].includes(url.protocol))throw new Error('Apenas URLs HTTP/HTTPS são aceitas.');url.hash='';for(const key of [...url.searchParams.keys()]){const lower=key.toLowerCase();if(lower.startsWith('utm_')||TRACKING_KEYS.has(lower))url.searchParams.delete(key);}const sorted=[...url.searchParams.entries()].sort(([a],[b])=>a.localeCompare(b));url.search='';sorted.forEach(([key,value])=>url.searchParams.append(key,value));return {originalRequestedUrl:original,normalizedUrl:url.toString()};}
function normalizeProductionInput(raw={}){const sourceType=clean(raw.sourceType||raw.type||'url',30).toLowerCase();if(!ALLOWED_SOURCE_TYPES.has(sourceType))throw new Error('Tipo de entrada inválido.');const slideCount=clamp(raw.slideCount||7,3,15);const title=clean(raw.title,220);const base={sourceType,slideCount,title,origin:'forma',createdBy:'forma-design'};if(sourceType==='url'){const url=normalizeUrl(raw.url);return {...base,...url,url:url.normalizedUrl};}if(sourceType==='text'){const text=clean(raw.text,120000);if(text.length<40)throw new Error('Cole um texto com pelo menos 40 caracteres.');return {...base,text};}if(sourceType==='topic'){const topic=clean(raw.topic||raw.text,4000);if(topic.length<8)throw new Error('Descreva a pauta com pelo menos 8 caracteres.');return {...base,topic};}const projectId=clean(raw.projectId,160);if(!projectId)throw new Error('Informe o projeto que será regenerado.');return {...base,projectId};}
function publicJob(row){if(!row)return null;return {id:row.id,sourceType:row.source_type,title:row.title,input:parseJson(row.normalized_input,{}),status:row.status,stage:row.stage,progress:Number(row.progress)||0,attempt:Number(row.attempt)||1,retryCount:Number(row.retry_count)||0,heartbeat:row.heartbeat,output:parseJson(row.output_payload,{}),error:parseJson(row.error_payload,{}),readerStrategy:row.reader_strategy||'',evidenceCount:Number(row.evidence_count)||0,qualityScore:row.quality_score==null?null:Number(row.quality_score),confidence:row.confidence==null?null:Number(row.confidence),engineBaseline:row.engine_baseline||'forma-production-v1',createdAt:row.created_at,updatedAt:row.updated_at};}
async function createJob(request,env){await ensure(env.DB);const raw=await request.json().catch(()=>({}));let normalized;try{normalized=normalizeProductionInput(raw);}catch(error){return json({ok:false,error:error.message||'Entrada inválida'},400);}const jobId=id(),ts=now();const title=clean(normalized.title||(normalized.sourceType==='url'?new URL(normalized.url).hostname:normalized.sourceType==='topic'?normalized.topic.slice(0,100):normalized.sourceType==='text'?normalized.text.slice(0,100):`Projeto ${normalized.projectId}`),220);await env.DB.prepare(`INSERT INTO ${TABLE}(id,source_type,title,input_payload,normalized_input,status,stage,progress,attempt,retry_count,heartbeat,output_payload,error_payload,reader_strategy,evidence_count,quality_score,confidence,engine_baseline,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(jobId,normalized.sourceType,title,JSON.stringify(raw),JSON.stringify(normalized),'queued','source',6,1,0,ts,'{}','{}','',0,null,null,'forma-production-v1',ts,ts).run();const row=await env.DB.prepare(`SELECT * FROM ${TABLE} WHERE id=?`).bind(jobId).first();return json({ok:true,job:publicJob(row),capabilities:{coordinator:true,reader:false,evidence:false,carousel:false},nextStage:'reader'},201);}
async function listJobs(env,url){await ensure(env.DB);const limit=clamp(url.searchParams.get('limit')||30,1,100);const rows=await env.DB.prepare(`SELECT * FROM ${TABLE} ORDER BY updated_at DESC LIMIT ?`).bind(limit).all();return json({ok:true,jobs:(rows.results||[]).map(publicJob)});}
async function getJob(jobId,env){await ensure(env.DB);const row=await env.DB.prepare(`SELECT * FROM ${TABLE} WHERE id=?`).bind(jobId).first();if(!row)return json({ok:false,error:'Job não encontrado'},404);return json({ok:true,job:publicJob(row)});}
async function retryJob(jobId,request,env){await ensure(env.DB);const row=await env.DB.prepare(`SELECT * FROM ${TABLE} WHERE id=?`).bind(jobId).first();if(!row)return json({ok:false,error:'Job não encontrado'},404);if(row.status==='cancelled')return json({ok:false,error:'Job cancelado não pode ser retomado.'},409);const body=await request.json().catch(()=>({}));const requestedStage=clean(body.stage,30).toLowerCase();const stage=ALLOWED_STAGES.has(requestedStage)&&!['ready','failed','cancelled'].includes(requestedStage)?requestedStage:'source';const ts=now();await env.DB.prepare(`UPDATE ${TABLE} SET status='queued',stage=?,progress=?,attempt=attempt+1,retry_count=retry_count+1,heartbeat=?,error_payload='{}',updated_at=? WHERE id=?`).bind(stage,stage==='source'?6:10,ts,ts,jobId).run();return getJob(jobId,env);}
async function cancelJob(jobId,env){await ensure(env.DB);const row=await env.DB.prepare(`SELECT * FROM ${TABLE} WHERE id=?`).bind(jobId).first();if(!row)return json({ok:false,error:'Job não encontrado'},404);if(row.status==='ready')return json({ok:false,error:'Job concluído não pode ser cancelado.'},409);const ts=now();await env.DB.prepare(`UPDATE ${TABLE} SET status='cancelled',stage='cancelled',heartbeat=?,updated_at=? WHERE id=?`).bind(ts,ts,jobId).run();return getJob(jobId,env);}
export async function handleFormaProductionApi(request,env){if(!env.DB)return json({ok:false,code:'DB_BINDING_REQUIRED',error:'Binding D1 DB não configurado'},503);const url=new URL(request.url);if(url.pathname==='/api/forma/production/jobs'&&request.method==='POST')return createJob(request,env);if(url.pathname==='/api/forma/production/jobs'&&request.method==='GET')return listJobs(env,url);const match=/^\/api\/forma\/production\/jobs\/([a-f0-9-]{20,80})(?:\/(retry|cancel))?$/i.exec(url.pathname);if(match&&!match[2]&&request.method==='GET')return getJob(match[1],env);if(match&&match[2]==='retry'&&request.method==='POST')return retryJob(match[1],request,env);if(match&&match[2]==='cancel'&&request.method==='POST')return cancelJob(match[1],env);return json({ok:false,error:'Endpoint não encontrado'},404);}
export { normalizeProductionInput, normalizeUrl };
